// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: media/media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // exp: "avatar.png"
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // exp: "image/png"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateURLRequest) Reset() {
	*x = GenerateURLRequest{}
	mi := &file_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateURLRequest) ProtoMessage() {}

func (x *GenerateURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateURLRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GenerateURLRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GenerateURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // Link for Frontend to upload directly to MinIO
	TmpPath       string                 `protobuf:"bytes,2,opt,name=tmp_path,json=tmpPath,proto3" json:"tmp_path,omitempty"`       // Temporary file storage path
	PerPath       string                 `protobuf:"bytes,3,opt,name=per_path,json=perPath,proto3" json:"per_path,omitempty"`       // Permanent file storage path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateURLResponse) Reset() {
	*x = GenerateURLResponse{}
	mi := &file_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateURLResponse) ProtoMessage() {}

func (x *GenerateURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateURLResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GenerateURLResponse) GetTmpPath() string {
	if x != nil {
		return x.TmpPath
	}
	return ""
}

func (x *GenerateURLResponse) GetPerPath() string {
	if x != nil {
		return x.PerPath
	}
	return ""
}

type CommitFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmpPath       string                 `protobuf:"bytes,1,opt,name=tmp_path,json=tmpPath,proto3" json:"tmp_path,omitempty"`
	PerPath       string                 `protobuf:"bytes,2,opt,name=per_path,json=perPath,proto3" json:"per_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitFileRequest) Reset() {
	*x = CommitFileRequest{}
	mi := &file_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitFileRequest) ProtoMessage() {}

func (x *CommitFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitFileRequest.ProtoReflect.Descriptor instead.
func (*CommitFileRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *CommitFileRequest) GetTmpPath() string {
	if x != nil {
		return x.TmpPath
	}
	return ""
}

func (x *CommitFileRequest) GetPerPath() string {
	if x != nil {
		return x.PerPath
	}
	return ""
}

type CommitFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitFileResponse) Reset() {
	*x = CommitFileResponse{}
	mi := &file_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitFileResponse) ProtoMessage() {}

func (x *CommitFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitFileResponse.ProtoReflect.Descriptor instead.
func (*CommitFileResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *CommitFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectPath    string                 `protobuf:"bytes,1,opt,name=object_path,json=objectPath,proto3" json:"object_path,omitempty"` // vd: "per/profiles/user1_xyz.jpg"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_media_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFileRequest) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_media_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_media_media_proto protoreflect.FileDescriptor

const file_media_media_proto_rawDesc = "" +
	"\n" +
	"\x11media/media.proto\x12\x05media\"m\n" +
	"\x12GenerateURLRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"j\n" +
	"\x13GenerateURLResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x19\n" +
	"\btmp_path\x18\x02 \x01(\tR\atmpPath\x12\x19\n" +
	"\bper_path\x18\x03 \x01(\tR\aperPath\"I\n" +
	"\x11CommitFileRequest\x12\x19\n" +
	"\btmp_path\x18\x01 \x01(\tR\atmpPath\x12\x19\n" +
	"\bper_path\x18\x02 \x01(\tR\aperPath\".\n" +
	"\x12CommitFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x11DeleteFileRequest\x12\x1f\n" +
	"\vobject_path\x18\x01 \x01(\tR\n" +
	"objectPath\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe3\x01\n" +
	"\fMediaService\x12M\n" +
	"\x14GeneratePresignedURL\x12\x19.media.GenerateURLRequest\x1a\x1a.media.GenerateURLResponse\x12A\n" +
	"\n" +
	"CommitFile\x12\x18.media.CommitFileRequest\x1a\x19.media.CommitFileResponse\x12A\n" +
	"\n" +
	"DeleteFile\x12\x18.media.DeleteFileRequest\x1a\x19.media.DeleteFileResponseB=Z;github.com/himbo22/xoxz/common-service/protobuf/media;mediab\x06proto3"

var (
	file_media_media_proto_rawDescOnce sync.Once
	file_media_media_proto_rawDescData []byte
)

func file_media_media_proto_rawDescGZIP() []byte {
	file_media_media_proto_rawDescOnce.Do(func() {
		file_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)))
	})
	return file_media_media_proto_rawDescData
}

var file_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_media_media_proto_goTypes = []any{
	(*GenerateURLRequest)(nil),  // 0: media.GenerateURLRequest
	(*GenerateURLResponse)(nil), // 1: media.GenerateURLResponse
	(*CommitFileRequest)(nil),   // 2: media.CommitFileRequest
	(*CommitFileResponse)(nil),  // 3: media.CommitFileResponse
	(*DeleteFileRequest)(nil),   // 4: media.DeleteFileRequest
	(*DeleteFileResponse)(nil),  // 5: media.DeleteFileResponse
}
var file_media_media_proto_depIdxs = []int32{
	0, // 0: media.MediaService.GeneratePresignedURL:input_type -> media.GenerateURLRequest
	2, // 1: media.MediaService.CommitFile:input_type -> media.CommitFileRequest
	4, // 2: media.MediaService.DeleteFile:input_type -> media.DeleteFileRequest
	1, // 3: media.MediaService.GeneratePresignedURL:output_type -> media.GenerateURLResponse
	3, // 4: media.MediaService.CommitFile:output_type -> media.CommitFileResponse
	5, // 5: media.MediaService.DeleteFile:output_type -> media.DeleteFileResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_media_proto_init() }
func file_media_media_proto_init() {
	if File_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_media_proto_goTypes,
		DependencyIndexes: file_media_media_proto_depIdxs,
		MessageInfos:      file_media_media_proto_msgTypes,
	}.Build()
	File_media_media_proto = out.File
	file_media_media_proto_goTypes = nil
	file_media_media_proto_depIdxs = nil
}
