events {
    worker_connections 1024;
}

http {
    # Disable buffering so Nginx streams directly to MinIO instead of storing on RAM/Disk
    proxy_buffering off;
    proxy_request_buffering off;
    
    # Allow large file uploads (e.g., 100MB)
    client_max_body_size 1m;

    # ==========================================
    # SERVER 1: API endpoint (Port 80 -> mapped to 8030)
    # ==========================================
    server {
        listen 80;
        server_name localhost;

        # Image upload and serving flow (S3 API)
        location / {
            proxy_pass http://minio:9000;
            
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # ==========================================
    # SERVER 2: Web Console UI (Port 666 -> mapped to 8031)
    # ==========================================
    server {
        listen 666;
        server_name localhost;

        proxy_http_version 1.1;

        # Run at root (/) to avoid broken static CSS/JS file paths
        location / {
            proxy_pass http://minio:9001;
            
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Keep your excellent Websocket configuration
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}