// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/himbo22/xoxz/livestream-service/internal/config"
	"github.com/himbo22/xoxz/livestream-service/internal/controller/http/livestream"
	"github.com/himbo22/xoxz/livestream-service/internal/controller/http/webhook"
	"github.com/himbo22/xoxz/livestream-service/internal/domain/repository/repo_impl"
	"github.com/himbo22/xoxz/livestream-service/internal/logic"
	"github.com/himbo22/xoxz/livestream-service/internal/service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	xoxzLogger, cleanup := provideAppLogger(cfg)
	database, cleanup2, err := provideMongoDatabase(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	livestreamRepository := repo_impl.NewLivestreamRepository(database)
	liveKitSDK, err := provideLiveKitSDK(cfg, xoxzLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	liveStreamLogic := logic.NewLiveStreamLogic(livestreamRepository, liveKitSDK, xoxzLogger)
	liveStreamService := service.NewLiveStreamService(liveStreamLogic)
	liveStreamController := livestream.NewLiveStreamController(xoxzLogger, liveStreamService)
	webhookController := webhook.NewWebhookController(cfg, xoxzLogger)
	controllers := provideControllers(liveStreamController, webhookController)
	echo := provideEchoApp(controllers, xoxzLogger)
	otelTracerToken, cleanup3, err := provideOtelCollector(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(cfg, echo, otelTracerToken)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
