// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/himbo22/xoxz/artist-service/internal/config"
	"github.com/himbo22/xoxz/artist-service/internal/controller/http/artist"
	"github.com/himbo22/xoxz/artist-service/internal/domain/repository/repo_impl"
	"github.com/himbo22/xoxz/artist-service/internal/logic"
	"github.com/himbo22/xoxz/artist-service/internal/service"
)

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	xoxzLogger, cleanup := provideAppLogger(cfg)
	db, cleanup2, err := providePostgreSQL(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	artistRepository := repo_impl.NewArtistRepository(db)
	artistLogic := logic.NewArtistLogic(xoxzLogger, artistRepository)
	artistService := service.NewArtistService(artistLogic)
	artistController := artist.NewArtistController(xoxzLogger, artistService)
	controllers := provideControllers(artistController)
	echo := provideEchoApp(controllers, xoxzLogger)
	otelTracerToken, cleanup3, err := provideOtelCollector(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(cfg, echo, otelTracerToken)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
