// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/himbo22/xoxz/media-service/internal/config"
	"github.com/himbo22/xoxz/media-service/internal/controller/http/media"
	"github.com/himbo22/xoxz/media-service/internal/service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	minioClient, err := provideMinioClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	mediaService := service.NewMediaService(minioClient)
	mediaController := media.NewMediaController(mediaService)
	controllers := provideControllers(mediaController)
	echo := provideEchoApp(controllers)
	mediaServer := provideGrpcServer(minioClient)
	app := NewApp(cfg, echo, mediaServer)
	return app, func() {
	}, nil
}
