// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/himbo22/xoxz/account-service/internal/config"
	"github.com/himbo22/xoxz/account-service/internal/controller/http/admin"
	"github.com/himbo22/xoxz/account-service/internal/controller/http/auth"
	"github.com/himbo22/xoxz/account-service/internal/controller/http/profile"
	"github.com/himbo22/xoxz/account-service/internal/domain/repository/repository_impl"
	"github.com/himbo22/xoxz/account-service/internal/logic"
	"github.com/himbo22/xoxz/account-service/internal/service"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	xoxzLogger, cleanup := provideAppLogger(cfg)
	db, cleanup2, err := providePostgreSQL(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := repository_impl.NewUserRepository(db)
	identityRepository := repository_impl.NewIdentityRepository(db)
	roleRepository := repository_impl.NewRoleRepository(db)
	userRoleRepository := repository_impl.NewUserRoleRepository(db)
	txRunner := repository_impl.NewTxManager(db)
	client, cleanup3, err := provideRedisClient(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisRepository := repository_impl.NewRedisRepository(client, xoxzLogger)
	authLogic := logic.NewAuthLogic(cfg, xoxzLogger, userRepository, identityRepository, roleRepository, userRoleRepository, txRunner, redisRepository)
	authService := service.NewAuthService(authLogic)
	authController := auth.NewAuthController(authService, xoxzLogger)
	mediaClient, cleanup4, err := provideGrpcMediaClient()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	profileLogic := logic.NewProfileLogic(cfg, xoxzLogger, mediaClient, userRepository)
	profileService := service.NewProfileService(profileLogic)
	profileController := profile.NewProfileController(profileService)
	rolePermissionRepository := repository_impl.NewRolePermissionRepository(db)
	permissionRepository := repository_impl.NewPermissionRepository(db)
	accessControl, cleanup5, err := provideAccessControl(rolePermissionRepository, permissionRepository)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	adminLogic := logic.NewAdminLogic(xoxzLogger, accessControl)
	adminService := service.NewAdminService(adminLogic)
	adminController := admin.NewAdminController(adminService, xoxzLogger)
	controllers := provideControllers(authController, profileController, adminController)
	authMiddleware := provideAuthMiddleware(redisRepository, accessControl)
	echo := provideEchoApp(controllers, xoxzLogger, authMiddleware)
	otelTracerToken, cleanup6, err := provideOtelCollector(cfg)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(cfg, echo, otelTracerToken)
	return app, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
