#apiVersion: 1
#
#datasources:
#  - name: Prometheus
#    type: prometheus
#    url: http://prometheus:9090
#    isDefault: true
#    editable: true
#
#  - name: Tempo
#    type: tempo
#    url: http://tempo:3200
#    editable: true
#    jsonData:
#      tracesToLogsV2:
#        datasourceUid: loki    # clicking a trace → jumps to logs
#      tracesToMetrics:
#        datasourceUid: prometheus
#      serviceMap:
#        datasourceUid: prometheus
#
#  - name: Loki
#    type: loki
#    url: http://loki:3100
#    editable: true
#    jsonData:
#      derivedFields:
#        - name: trace_id
#          matcherRegex: "trace_id=(\\w+)"
#          url: "$${__value.raw}"
#          datasourceUid: tempo  # clicking trace_id in logs → jumps to Tempo